### ISSUE TITLE
你好，我想问下我得到的结果怎么

### ISSUE THREAD

**Issue by LukeGoldberg** [jcyk/CWS#1]
形如这样的结果:
 \  x  e  4                              \  x  b  8 
这是啥啊......

**Comment by jcyk** [comment]
Please provide more information in case you still have a question. :)

**Comment by LukeGoldberg** [comment]
thanks for your code.:)
i have run your code, and the result file is a style like "\ x e 4 \ x b 8".
i know the result is right, and it is Hexadecimal to present chinese word in Python2.x, but i have not found a solution to translate it back. i know i can use the decode('utf8') function, but i have not understand your function "output_result" yet, can u check it?
by the way, u r not chinese? :)

**Comment by jcyk** [comment]
I am practicing my English, Haha.
1. Split sentence into short sentences by the occurrences of punctuations.
2. Sort short sentences by length. (to accelerate the minibatch-style work)
3. Segment them and return the results to corresponding positions.
