### ISSUE TITLE
Help wanted: Training the model with my own corpus causes ValueError

### ISSUE THREAD

**Issue by reid3290** [jcyk/CWS#2]
I'm trying to train the model with my own corpus, but it failed with this error:
![image](https://user-images.githubusercontent.com/9301137/28362705-f8b63e12-6caf-11e7-8e30-bee35a767914.png)
![image](https://user-images.githubusercontent.com/9301137/28362714-0b31d11e-6cb0-11e7-8480-77d0ac854865.png)
I highlight the important lines, which apparently some matrices' dimension is not compatible to do matrix multiple: `numpy.dot(A,x)`。But all I did is just replace the corpus with my own one, really don't know why this is happening. Is there any requirement for corpus or whatever other reasons that i can not figure out.

**Comment by jcyk** [comment]
I am not sure.
But please ensure that the words in training data do not exceed the maximum word length setting.

**Comment by reid3290** [comment]
Yes, that's exactly the problem. Thanks for reminding.
